server:
  port: 8081
  tomcat:
    max-threads: 30
    
---
spring:
  datasource:
    platform: h2
    url: jdbc:h2:mem:test;MODE=MySQL;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=TRUE
    schema: classpath*:db/initDB.sql
    data:   classpath*:db/populateDB.sql
    username: sa
    password:
    driverClassName: org.h2.Driver
    hikari:
      maximum-pool-size: 10
  h2:
    console:
      enabled: true
      path: /console
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    show-sql: true
    hibernate:
      ddl-auto: none

---
application:
  environment: Development

---
